      - name: Commit output files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch
          git pull --rebase
          git add output/*
          git status
          git diff --cached
          git commit -m "Add daily scraped articles" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
